# Generated by Django 4.1.3 on 2022-11-21 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='tx_name', max_length=36, verbose_name='Nome')),
                ('altura', models.DecimalField(db_column='nb_altura', decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('tipo', models.CharField(choices=[('Agua', 'Agua'), ('Fogo', 'Fogo'), ('Planta', 'Planta'), ('Eletrico', 'Eletrico')], db_column='cs_tipo', max_length=16, verbose_name='Tipo')),
                ('peso', models.DecimalField(db_column='nb_peso', decimal_places=2, max_digits=4, verbose_name='Peso')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], db_column='cs_sexo', max_length=5, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
                'db_table': 'pokemon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(db_column='tx_lugar', max_length=15, verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Regiao',
                'verbose_name_plural': 'Regioes',
                'db_table': 'Regiao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='tx_name', max_length=36, verbose_name='Nome')),
                ('altura', models.DecimalField(db_column='nb_altura', decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('idade', models.IntegerField(db_column='nb_idade', verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminno', 'Femino')], db_column='cs_sexo', max_length=16, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Treinador',
                'verbose_name_plural': 'Treinadores',
                'db_table': 'Treinador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemon')),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.treinador')),
            ],
        ),
    ]
