# Generated by Django 4.1.3 on 2022-11-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='tx_name', max_length=36, verbose_name='Nome')),
                ('altura', models.DecimalField(db_column='nb_altura', decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('tipo', models.CharField(choices=[('Agua', 'Agua'), ('Fogo', 'Fogo'), ('Planta', 'Planta'), ('Eletrico', 'Eletrico')], db_column='cs_tipo', max_length=16, verbose_name='Tipo')),
                ('peso', models.DecimalField(db_column='nb_peso', decimal_places=2, max_digits=4, verbose_name='Peso')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], db_column='cs_sexo', max_length=5, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
                'db_table': 'pokemon',
                'managed': True,
            },
        ),
    ]
