# Generated by Django 4.1.3 on 2022-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='tx_name', max_length=36, verbose_name='Nome')),
                ('altura', models.DecimalField(db_column='nb_altura', decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('idade', models.IntegerField(db_column='nb_idade', verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminno', 'Femino')], db_column='cs_sexo', max_length=16, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Treinador',
                'verbose_name_plural': 'Treinadores',
                'db_table': 'Treinador',
                'managed': True,
            },
        ),
    ]
