# Generated by Django 4.1.3 on 2022-11-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_treinador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Regiao',
                'verbose_name_plural': 'Regioes',
                'db_table': 'Regiao',
                'managed': True,
            },
        ),
    ]
