# Generated by Django 4.1.3 on 2022-11-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_regiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiao',
            name='lugar',
            field=models.CharField(choices=[('Kanto', 'Kanto'), ('Johto', 'Johto'), ('Hoenn', 'Hoenn'), ('Sinnoh', 'Sinnoh'), ('Unova', 'Unova'), ('Kalos', 'Kalos'), ('Alola', 'Alola'), ('Galar', 'Galar')], db_column='cs_lugar', default='Kanto', max_length=6, verbose_name='Lugar'),
        ),
    ]
