# Generated by Django 4.1.3 on 2022-11-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_regiao_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiao',
            name='lugar',
            field=models.CharField(db_column='tx_lugar', max_length=10, verbose_name='Lugar'),
        ),
    ]
